#!/bin/sh

: ${CC:=winegcc -m32 -mno-cygwin}
: ${CFLAGS:=-Og -fstack-clash-protection -fstack-protector-strong -ggdb3 -mtune=native}

: ${WINAMP_SDK_DIR:=~/.wine/drive_c/Program Files (x86)/Winamp SDK}
: ${PREFIX:=~/.local}

CFLAGS="
 -DNTDDI_VERSION=NTDDI_WIN7
 -D_WIN32_WINNT=_WIN32_WINNT_WIN7
 -DWINVER=_WIN32_WINNT_WIN7
 -Wall -Wextra -Wpedantic
 $CFLAGS"

main() {
	case ${1:-default} in
	default) main build && main install;;
	build)
		if [ ! -d "$WINAMP_SDK_DIR" ]; then
			cat <<- ! >&2
			ERROR: winamp sdk not found in '$WINAMP_SDK_DIR'
			download it from http://wiki.winamp.com/wiki/Plug-in_Developer#SDK_Documentation and try again
			!
			return 1
		fi
		( set -x; exec $CC -I"$WINAMP_SDK_DIR" $CFLAGS -o ddw_host.exe main.c )
		;;
	install)
		install -Dv ddw_host.exe "$PREFIX"/bin/ddw_host.exe
		install -Dv ddw_host.exe.so "$PREFIX"/bin/ddw_host.exe.so
		case :$PATH: in
		*:"$PREFIX"/bin:*);;
		*) >&2 echo "note: $PREFIX/bin not found in PATH"
		esac
		;;
	watch) shift; printf '%s\n' main.c ../common.h | entr -c sh -c 'date; exec ./build "$@"' -- "$@";;
	*) >&2 echo "$0: unknown target $1"; return 1;;
	esac
}
main "$@"
