#!/bin/sh

: ${CC:=gcc}
: ${CFLAGS:=-Og -fstack-clash-protection -fstack-protector-strong -ggdb3 -mtune=native}
: ${PREFIX:=~/.local}

CFLAGS="
 -Wall -Wextra -Wpedantic
 -DDDB_API_LEVEL=10
 -DDDB_WARN_DEPRECATED=1
 -fPIC -shared
 $CFLAGS"

main() {
	case ${1:-default} in
	default) main build && main install;;
	build) ( set -x; exec $CC $CFLAGS -o dsp_winamp.so plugin.c );;
	install) install -Dv dsp_winamp.so "$PREFIX"/lib/deadbeef/dsp_winamp.so;;
	*) >&2 echo "$0: unknown target $1"; return 1;;
	esac
}
main "$@"
